angular.module('sortApp', [])

.controller('mainController', function($scope) {
	$scope.sortType     = 'album';
	$scope.sortReverse  = false;  
	$scope.searchartist   = '';  
	
	
	
	$scope.list = [
		{ album: '....Lifun', artist: 'Trubrot', year: '1971', rating: '★★★'},
		{ album: '...Sounds Like This', artist: 'Nektar', year: '1973', rating: ''},
		{ album: '1000 Autunni', artist: 'Ske', year: '2011', rating: '★'},
		{ album: '1001° Centigrades', artist: 'Magma', year: '1971', rating: ''},
		{ album: '10cc', artist: '10cc', year: '1973', rating: '★★'},
		{ album: '1973', artist: 'Placebo', year: '1973', rating: ''},
		{ album: '1990', artist: 'Solaris', year: '1990', rating: ''},
		{ album: '1998 La Storia Di S\'abazio', artist: 'Triade', year: '1973', rating: '★'},
		{ album: '200 Years After The Last War', artist: 'Omega', year: '1973', rating: ''},
		{ album: '20000 Miles Under The Sea', artist: 'Nautilus', year: '1978', rating: '★★★'},
		{ album: '2001', artist: 'Amanda Shankar', year: '1984', rating: ''},
		{ album: '2023', artist: 'Bans Manco', year: '1975', rating: ''},
		{ album: '2375004', artist: 'Ihre Kinder', year: '1970', rating: ''},
		{ album: '25 Years On', artist: 'Hawklords', year: '1978', rating: ''},
		{ album: '2973 La Nemica Dei Ricordi', artist: 'Spettri', year: '2015', rating: ''},
		{ album: '2Nd', artist: 'Agitation Free', year: '1973', rating: ''},
		{ album: '3', artist: 'Ekseption', year: '1970', rating: ''},
		{ album: '3:E Skivan', artist: 'Mikael Ramel', year: '1977', rating: ''},
		{ album: '4 Visions', artist: 'Eskaton', year: '1979', rating: ''},
		{ album: '666', artist: 'Aphrodites Child', year: '1972', rating: ''},
		{ album: '801 Live', artist: '801', year: '1984', rating: ''},
		{ album: '9 Parts To The Wind', artist: 'Strange Days', year: '1975', rating: ''},
		{ album: 'A Breath Of Fresh Air', artist: 'Albatross', year: '1973', rating: ''},
		{ album: 'A Funky Thide Of Sings', artist: 'Billy Cobham', year: '1975', rating: '★'},
		{ album: 'A Jug Of Love', artist: 'Mighty Baby', year: '1971', rating: ''},
		{ album: 'A L\'Aube Du Versea', artist: 'Elohim', year: '1975', rating: ''},
		{ album: 'A Musical Evening With The Mick Abrahams Band', artist: 'Mick Abrahams', year: '1971', rating: ''},
		{ album: 'A Nice Way Of Love', artist: 'Cruciferius', year: '1970', rating: ''},
		{ album: 'A Question Of Balance', artist: 'The Moody Blues', year: '1970', rating: ''},
		{ album: 'A Rohanas', artist: 'Skorpio', year: '1974', rating: ''},
		{ album: 'A Salty Dog', artist: 'Procol Harum', year: '1969', rating: '★★★'},
		{ album: 'A Scarcity Of Miracles', artist: 'Jakszyk, Fripp, And Collins', year: '2011', rating: ''},
		{ album: 'A Tab In The Ocean', artist: 'Nektar', year: '1972', rating: '★★★'},
		{ album: 'A Third Of A Lifetime', artist: 'Three Man Army', year: '1971', rating: ''},
		{ album: 'A Toast To Panama Red', artist: 'Master\'S Apprentices', year: '1972', rating: ''},
		{ album: 'A Trick Of The Trail', artist: 'Genesis', year: '1975', rating: ''},
		{ album: 'A Way Of Express', artist: 'Sisyphos', year: '1981', rating: ''},
		{ album: 'A.R. Iv', artist: 'Achim Reichel & Machines', year: '1973', rating: ''},
		{ album: 'A=Mh2', artist: 'Clark-Hutchinson', year: '1969', rating: ''},
		{ album: 'About The Black Eyed Girl', artist: 'Indisciplined Lucky', year: '1999', rating: ''},
		{ album: 'Abrakadabra', artist: 'Klockwerk Orange', year: '1975', rating: ''},
		{ album: 'Abraxas', artist: 'Santana', year: '1970', rating: ''},
		{ album: 'Acoustics', artist: 'Aquarium', year: '1982', rating: ''},
		{ album: 'Acquiring The Taste', artist: 'Gentle Giant', year: '1971', rating: ''},
		{ album: 'Act One', artist: 'Beggars Opera', year: '1970', rating: ''},
		{ album: 'Ad Gloriam', artist: 'Le Orme', year: '1969', rating: ''},
		{ album: 'Adonis', artist: 'Anyone\'S Daughter', year: '1979', rating: '★★★★'},
		{ album: 'Aerie Faerie Nonsense', artist: 'The End', year: '1977', rating: ''},
		{ album: 'Aerolit', artist: 'Czeslaw Niemen', year: '1975', rating: ''},
		{ album: 'The Aerosol Grey Machine', artist: 'Van Der Graaf Generator', year: '1969', rating: ''},
		{ album: 'Affinity', artist: 'Affinity', year: '1970', rating: ''},
		{ album: 'Affresco', artist: 'Franco Maria Giannini', year: '1974', rating: ''},
		{ album: 'Afreaka', artist: 'Demon Fuzz', year: '1970', rating: ''},
		{ album: 'After The War', artist: 'Trouble', year: '1970', rating: ''},
		{ album: 'Agusa', artist: 'Agusa', year: '2017', rating: ''},
		{ album: 'Ahead Rings Out', artist: 'Bloodwyn Pig', year: '1969', rating: '★'},
		{ album: 'Ahmoo', artist: 'Jupu Group', year: '1975', rating: ''},
		{ album: 'Ailleurs', artist: 'Dominique Blanc-Francard', year: '1972', rating: ''},
		{ album: 'Air Conditioning', artist: 'Curved Air', year: '1970', rating: ''},
		{ album: 'Alas', artist: 'Alas', year: '1976', rating: ''},
		{ album: 'Albatross', artist: 'Albatross', year: '1976', rating: ''},
		{ album: 'Ali Baba', artist: 'Chute Libre', year: '1978', rating: ''},
		{ album: 'Alice', artist: 'Alice', year: '1970', rating: ''},
		{ album: 'Al-Jadida', artist: 'Rabih Abou-Khalil', year: '1991', rating: ''},
		{ album: 'All Our Hopes', artist: 'Mcoil', year: '1979', rating: ''},
		{ album: 'All Together Now', artist: 'Argent', year: '1972', rating: ''},
		{ album: 'All Will Be Changed', artist: 'Frumpy', year: '1970', rating: ''},
		{ album: 'All-Bumm', artist: '18 Karat Gold', year: '1973', rating: ''},
		{ album: 'Allez Teia', artist: 'Heldon', year: '1975', rating: ''},
		{ album: 'Almendra', artist: 'Almendra', year: '1969', rating: ''},
		{ album: 'Almost Tender', artist: 'Solenoid', year: '1977', rating: ''},
		{ album: 'Alpha Centauri', artist: 'Alpha Centurus', year: '1973', rating: ''},
		{ album: 'Alphataurus', artist: 'Alphataurus', year: '1973', rating: ''},
		{ album: 'Alshia', artist: 'Alshia', year: '1980', rating: ''},
		{ album: 'Altona', artist: 'Altona', year: '1974', rating: ''},
		{ album: 'Alturas De Macchu Picchu', artist: 'Los Jaivas', year: '1981', rating: ''},
		{ album: 'Alux Nahual', artist: 'Alux Nahual', year: '1980', rating: ''},
		{ album: 'Amenophis', artist: 'Amenophis', year: '1983', rating: '★★★'},
		{ album: 'Americanos', artist: 'Contraluz', year: '1973', rating: ''},
		{ album: 'Ammerland', artist: 'Fuhrs & Frohling', year: '1978', rating: ''},
		{ album: 'Amputechture', artist: 'The Mars Volta', year: '2006', rating: ''},
		{ album: 'An Asylum For The Musically Insane', artist: 'Tea And Symphony', year: '1969', rating: ''},
		{ album: 'An Escape From A Box', artist: 'Circus 2000', year: '1972', rating: ''},
		{ album: 'An Old Castle Of Transylvania', artist: 'Cosmos Factory', year: '1973', rating: ''},
		{ album: 'Anabelas', artist: 'Bubu', year: '1978', rating: ''},
		{ album: 'Ananda Shankar', artist: 'Ananda Shankar', year: '1970', rating: ''},
		{ album: 'Ananda Shankar', artist: 'Ananda Shankar And His Music', year: '1975', rating: ''},
		{ album: 'Andaluza', artist: 'Vega', year: '1978', rating: ''},
		{ album: 'Angel\'S Egg', artist: 'Gong', year: '1973', rating: ''},
		{ album: 'Angherr Shisspa', artist: 'Koenji Hyakkei', year: '2005', rating: '★'},
		{ album: 'Anomaly', artist: 'Mcluhan', year: '1972', rating: ''},
		{ album: 'Antologia', artist: 'Era Di Acquario', year: '1973', rating: ''},
		{ album: 'Anyone\'S Daughter', artist: 'Anyone\'S Daughter', year: '1980', rating: ''},
		{ album: 'Apocalipsis', artist: 'Aguaviva', year: '1971', rating: ''},
		{ album: 'Apoteosi', artist: 'Apoteosi', year: '1975', rating: ''},
		{ album: 'Aqualung', artist: 'Jethro Tull', year: '1971', rating: '★★★★'},
		{ album: 'Aranjuez', artist: 'Jan Akkerman - Claus Ogerman', year: '1978', rating: ''},
		{ album: 'Arbeit Macht Frei', artist: 'Area', year: '1973', rating: ''},
		{ album: 'Arbete Och Fritid', artist: 'Arbete Och Fritid', year: '1970', rating: ''},
		{ album: 'Archaia', artist: 'Archaia', year: '1977', rating: ''},
		{ album: 'Arco Iris', artist: 'Arco Iris', year: '1970', rating: ''},
		{ album: 'Aria', artist: 'Alan Sorrenti', year: '1972', rating: ''},
		{ album: 'Ark 2', artist: 'Flaming Youth', year: '1969', rating: ''},
		{ album: 'The Armada', artist: 'Rainbow Theatre', year: '1975', rating: ''},
		{ album: 'Arrow Head', artist: 'Osage Tribe', year: '1972', rating: ''},
		{ album: 'Ars Longa Vida Brevis', artist: 'Haddad', year: '2004', rating: ''},
		{ album: 'Artuad', artist: 'Prescado Rabioso', year: '1973', rating: ''},
		{ album: 'As Criancas Da Nova Floresta', artist: 'Recordando O Vale Das Macas', year: '1977', rating: ''},
		{ album: 'As Your Mind Flies By', artist: 'Rare Bird', year: '1970', rating: ''},
		{ album: 'Asa Nisi Masa', artist: 'Dolores', year: '1978', rating: ''},
		{ album: 'Asfalto', artist: 'Asfalto', year: '1978', rating: ''},
		{ album: 'Ash Ra Tempel', artist: 'Ash Ra Tempel', year: '1971', rating: ''},
		{ album: 'Ashes Are Burning', artist: 'Renaissance', year: '1973', rating: '★★★★'},
		{ album: 'The Asmoto Running Band', artist: 'Principal Edwards Magic Theatre', year: '1971', rating: ''},
		{ album: 'Astral Projector', artist: 'Zon', year: '1978', rating: ''},
		{ album: 'Astrolabio', artist: 'Garybaldi', year: '1973', rating: ''},
		{ album: 'Asylum', artist: 'Cressida', year: '1971', rating: ''},
		{ album: 'At The Mountains Of Madness', artist: 'Blackfeather', year: '1971', rating: ''},
		{ album: 'Atlantide', artist: 'Atlantide', year: '1976', rating: ''},
		{ album: 'Atlantis', artist: 'Earth And Fire', year: '1973', rating: ''},
		{ album: 'Atomic Rooster', artist: 'Atomic Rooster', year: '1970', rating: ''},
		{ album: 'Attosecondo', artist: 'Alphataurus', year: '2012', rating: ''},
		{ album: 'Au Nord De Notre Vie', artist: 'Cano', year: '1977', rating: ''},
		{ album: 'Aucan', artist: 'Aucan', year: '1977', rating: ''},
		{ album: 'Au-Dela Du Delire', artist: 'Ange', year: '1974', rating: ''},
		{ album: 'August 9Th', artist: 'Tranzam', year: '1975', rating: ''},
		{ album: 'Aura', artist: 'Aura', year: '1971', rating: ''},
		{ album: 'Ausschub', artist: 'Eulenspygel', year: '1972', rating: ''},
		{ album: 'Automatic Fine Tuning', artist: 'A.F.T.', year: '1976', rating: ''},
		{ album: 'Automatic Man', artist: 'Automatic Man', year: '1976', rating: ''},
		{ album: 'Autumn Grass', artist: 'Continuum', year: '1971', rating: ''},
		{ album: 'Ave Rock', artist: 'Ave Rock', year: '1974', rating: ''},
		{ album: 'Ave Sangria', artist: 'Ave Sangria', year: '1975', rating: ''},
		{ album: 'Avenida Larco', artist: 'Fragil', year: '1981', rating: ''},
		{ album: 'Awake', artist: 'Ticket', year: '1972', rating: ''},
		{ album: 'Axis', artist: 'Axis', year: '1973', rating: ''},
		{ album: 'Axis', artist: 'Terra Mystica', year: '2002', rating: ''},
		{ album: 'Ayeri Y Guei', artist: 'Nuberu', year: '1978', rating: ''},
		{ album: 'Azahar', artist: 'Azahar', year: '1979', rating: ''},
		{ album: 'Αγάπανθος (Agapanthos)', artist: 'Αγάπανθος (Agapanthos)', year: '1976', rating: ''},
		{ album: 'Babylon', artist: 'Babylon', year: '1978', rating: ''},
		{ album: 'Back Into The Future', artist: 'Man', year: '1973', rating: ''},
		{ album: 'Back To Thunder', artist: 'Strife', year: '1978', rating: ''},
		{ album: 'Ballettirosadimacchia', artist: 'Ballettirosadimacchia', year: '1974', rating: ''},
		{ album: 'Banco', artist: 'Banco Del Mutuo Soccorso', year: '1975', rating: ''},
		{ album: 'Banco Del Mutuo Soccorso', artist: 'Banco Del Mutuo Soccorso', year: '1972', rating: ''},
		{ album: 'Bandolier', artist: 'Budgie', year: '1975', rating: ''},
		{ album: 'Banquet', artist: 'Lucifer\'S Friend', year: '1974', rating: ''},
		{ album: 'Bao', artist: 'Yonin Bayashi', year: '1978', rating: ''},
		{ album: 'Barndomens Stigar', artist: 'Kulticator', year: '1981', rating: ''},
		{ album: 'Barrabas', artist: 'Barrabas', year: '1972', rating: ''},
		{ album: 'Barren Dream', artist: 'Mr. Sirius', year: '1987', rating: ''},
		{ album: 'Basket Of Light', artist: 'Pentangle', year: '1969', rating: ''},
		{ album: 'Be Do Have', artist: 'Thom Mason', year: '1980', rating: ''},
		{ album: 'Beat', artist: 'King Crimson', year: '1982', rating: ''},
		{ album: 'Beat-Oratorium', artist: 'Golgatha', year: '1974', rating: ''},
		{ album: 'Beautiful Lies', artist: 'Stamatis', year: '1971', rating: ''},
		{ album: 'Beauty\'S Song', artist: 'Stan Samnole', year: '1981', rating: ''},
		{ album: 'Beckett', artist: 'Beckett', year: '1974', rating: ''},
		{ album: 'Beginnings', artist: 'Steve Howe', year: '1975', rating: ''},
		{ album: 'Being', artist: 'Wigwam', year: '1974', rating: ''},
		{ album: 'Bells, Boots, And Shambles', artist: 'Spirogyra', year: '1973', rating: ''},
		{ album: 'Benzaiten', artist: 'Osamu Kitajima', year: '1976', rating: ''},
		{ album: 'Between Flesh And Divine', artist: 'Asia Minor', year: '1980', rating: ''},
		{ album: 'Between The Universes', artist: 'Tritonus', year: '1976', rating: ''},
		{ album: 'Beyond Expression', artist: 'Finch', year: '1976', rating: ''},
		{ album: 'Beyond Panic', artist: 'Pacific Eardrum', year: '1978', rating: ''},
		{ album: 'Biglietto Per L\'Inferno', artist: 'Biglietto Per L\'Inferno', year: '1974', rating: ''},
		{ album: 'Birds Of Fire', artist: 'The Mahavishu Orchestra', year: '1972', rating: ''},
		{ album: 'Bitter Harvest', artist: 'Rabih Abou-Khalil', year: '1984', rating: ''},
		{ album: 'Bizitako Gauzak', artist: 'Sakre', year: '1978', rating: ''},
		{ album: 'Bla Vardog', artist: 'Atlas', year: '1979', rating: ''},
		{ album: 'Black And White', artist: 'Vanessa', year: '1976', rating: ''},
		{ album: 'Black Hole', artist: 'Cosmos Factory', year: '1976', rating: ''},
		{ album: 'Black Hole Star', artist: 'The Neutrons', year: '1974', rating: ''},
		{ album: 'Black Magician', artist: 'Rumplestilskin', year: '1971', rating: ''},
		{ album: 'Black Noise', artist: 'Fm', year: '1978', rating: ''},
		{ album: 'Black Ship', artist: 'Sadistic Mika Band', year: '1974', rating: ''},
		{ album: 'Black Widow', artist: 'Black Widow', year: '1970', rating: ''},
		{ album: 'Blake\'S New Jerusalem', artist: 'Tim Blake', year: '1978', rating: ''},
		{ album: 'Blitzkrieg', artist: 'Wallenstein', year: '1972', rating: ''},
		{ album: 'Blops', artist: 'Blops', year: '1970', rating: ''},
		{ album: 'Bloque', artist: 'Bloque', year: '1978', rating: ''},
		{ album: 'Blow By Blow', artist: 'Jeff Beck', year: '1975', rating: ''},
		{ album: 'Blue Camel', artist: 'Rabih Abou-Khalil', year: '1992', rating: ''},
		{ album: 'Blurring The Lines .​.​.​A Democracy Manifest', artist: 'Ovrfwrd', year: '2018', rating: ''},
		{ album: 'Book M', artist: 'Secret Chiefs 3', year: '2001', rating: ''},
		{ album: 'Book Of Hours', artist: 'Willowglass', year: '2008', rating: ''},
		{ album: 'The Book Of Invasions', artist: 'Horslips', year: '1976', rating: '★★★'},
		{ album: 'Boris', artist: 'Yezda Urfa', year: '1975', rating: ''},
		{ album: 'Brain Salad Surgery', artist: 'Emerson, Lake, & Palmer', year: '1973', rating: ''},
		{ album: 'Breaking Barriers', artist: 'Tribute', year: '1986', rating: ''},
		{ album: 'Breathless', artist: 'Camel', year: '1978', rating: ''},
		{ album: 'Brian Auger\'S Oblivion Express', artist: 'Brian Auger\'S Oblivion Express', year: '1973', rating: ''},
		{ album: 'Broken Barricades', artist: 'Procol Harum', year: '1971', rating: ''},
		{ album: 'Broselmaschine', artist: 'Broselmaschine', year: '1971', rating: ''},
		{ album: 'Brother Bait', artist: 'Brother Bait', year: '1976', rating: ''},
		{ album: 'Bull Angus', artist: 'Bull Angus', year: '1971', rating: ''},
		{ album: 'Burning Candle', artist: 'Burning Candle', year: '1981', rating: ''},
		{ album: 'Burnt Suite', artist: 'Burnt Suite', year: '1972', rating: ''},
		{ album: 'Bury My Heart At Wounded Knee', artist: 'Gila', year: '1973', rating: ''},
		{ album: 'Busy Making Progress', artist: 'Progress', year: '1978', rating: ''},
		{ album: 'C.C.S.', artist: 'Ccs', year: '1970', rating: ''},
		{ album: 'Cactus Choir', artist: 'Dave Greenslade', year: '1976', rating: ''},
		{ album: 'Cada Vez Mas Cerca', artist: 'Aguaviva', year: '1970', rating: ''},
		{ album: 'Camel', artist: 'Camel', year: '1973', rating: ''},
		{ album: 'Camenbert Electrique', artist: 'Gong', year: '1971', rating: ''},
		{ album: 'Camere Zimmer Rooms', artist: 'Picchio Dal Pozzo', year: '2001', rating: ''},
		{ album: 'Campo Di Marte', artist: 'Campo Di Marte', year: '1973', rating: ''},
		{ album: 'Canis Iupus', artist: 'Darryl Way\'S Wolf', year: '1973', rating: ''},
		{ album: 'Cantafabule', artist: 'Phoenix', year: '1975', rating: ''},
		{ album: 'Captain Beyond', artist: 'Captain Beyond', year: '1972', rating: ''},
		{ album: 'Caravan', artist: 'Caravan', year: '1969', rating: ''},
		{ album: 'Caravanserai', artist: 'Santana', year: '1972', rating: ''},
		{ album: 'Carnascialia', artist: 'Carnascialia', year: '1979', rating: ''},
		{ album: 'Caronte', artist: 'The Trip', year: '1971', rating: ''},
		{ album: 'Castle In The Air', artist: 'Negasphere', year: '1984', rating: ''},
		{ album: 'Catapilla', artist: 'Catapilla', year: '1971', rating: ''},
		{ album: 'Caution Radiation Area', artist: 'Area', year: '1974', rating: ''},
		{ album: 'Cei Ce Ne-Au Dat Nume', artist: 'Phoenix', year: '1972', rating: ''},
		{ album: 'Charge', artist: 'Paladin', year: '1972', rating: '★★★'},
		{ album: 'Chede Chokra\'S', artist: 'Shark Move', year: '1970', rating: ''},
		{ album: 'Cherry Five', artist: 'Cherry Five', year: '1974', rating: ''},
		{ album: 'Chico Magnetic Band', artist: 'Chico Magnetic Band', year: '1973', rating: ''},
		{ album: 'Child Of The Novelty', artist: 'Mahogany Rush', year: '1974', rating: ''},
		{ album: 'The Children Of Lir', artist: 'Loudest Whisper', year: '1974', rating: ''},
		{ album: 'Choice Cuts', artist: 'Master\'S Apprentices', year: '1971', rating: ''},
		{ album: 'Choice Quality Stuff/Anytime', artist: 'It\'S A Beautiful Day', year: '1971', rating: ''},
		{ album: 'Ciclos', artist: 'Canarios', year: '1975', rating: ''},
		{ album: 'Circoncolutions', artist: 'Carpe Diem', year: '2015', rating: ''},
		{ album: 'Circumvision', artist: 'Kracq', year: '1978', rating: ''},
		{ album: 'Circus', artist: 'Argent', year: '1975', rating: ''},
		{ album: 'Circus 2000', artist: 'Circus 2000', year: '1970', rating: ''},
		{ album: 'City Lips', artist: 'Vanessa', year: '1975', rating: ''},
		{ album: 'City Of The Lips', artist: 'Heliopolis', year: '2014', rating: ''},
		{ album: 'The Civil Surface', artist: 'Egg', year: '1974', rating: ''},
		{ album: 'Clear Light Symphony', artist: 'Clearlight', year: '1975', rating: ''},
		{ album: 'Clockwyze', artist: 'Project Tyme', year: '1984', rating: ''},
		{ album: 'Close To The Edge', artist: 'Yes', year: '1972', rating: '★★★★★'},
		{ album: 'Clot 20', artist: 'Blay Tritono', year: '1976', rating: ''},
		{ album: 'Coffee In Neukolln', artist: 'Barock Project', year: '2012', rating: ''},
		{ album: 'Collegium Musicum', artist: 'Collegium Musicum', year: '1971', rating: ''},
		{ album: 'Color Humano', artist: 'Color Humano', year: '1972', rating: ''},
		{ album: 'Color Humano Ii', artist: 'Color Humano', year: '1973', rating: ''},
		{ album: 'Color Hunano Iii', artist: 'Color Humano', year: '1973', rating: ''},
		{ album: 'Come In Un\'Ultima Cena', artist: 'Banco Del Mutuo Soccorso', year: '1976', rating: ''},
		{ album: 'Commit Thyself', artist: 'The Music Asylum', year: '1970', rating: ''},
		{ album: 'Composition', artist: 'Gregory Kirby', year: '1978', rating: ''},
		{ album: 'Confesiones De Invierno', artist: 'Sui Generis', year: '1973', rating: ''},
		{ album: 'Conquista', artist: 'Alux Nahual', year: '1982', rating: ''},
		{ album: 'The Construkction Of Light', artist: 'King Crimson', year: '2000', rating: ''},
		{ album: 'Contaminazione', artist: 'Il Rovescio Della Medaglia', year: '1973', rating: ''},
		{ album: 'Contes Musicaux', artist: 'Michel Ripoche & Andre Demay', year: '1977', rating: ''},
		{ album: 'Continental Circus', artist: 'Gong', year: '1971', rating: ''},
		{ album: 'Contre Courant', artist: 'Opus 5', year: '1976', rating: ''},
		{ album: 'Coses Nostres', artist: 'Iceberg', year: '1976', rating: ''},
		{ album: 'The Cosmic Jokers', artist: 'The Cosmic Jokers', year: '1973', rating: ''},
		{ album: 'Couleurs De Temps', artist: 'Daniel Hass & Yves Hasselmann', year: '1978', rating: ''},
		{ album: 'The Courage Of Others', artist: 'Midlake', year: '2010', rating: ''},
		{ album: 'Crac!', artist: 'Area', year: '1974', rating: ''},
		{ album: 'Crafty Hands', artist: 'Happy The Man', year: '1978', rating: ''},
		{ album: 'The Crazy World Of Arthur Brown', artist: 'Arthur Brown', year: '1968', rating: ''},
		{ album: 'Cressidea', artist: 'Cressidea', year: '1970', rating: ''},
		{ album: 'Crime Of The Century', artist: 'Supertramp', year: '1974', rating: '★★★★★'},
		{ album: 'Crna Dama', artist: 'Smak', year: '1977', rating: ''},
		{ album: 'Cronologia Ii', artist: 'El Reloj', year: '1976', rating: ''},
		{ album: 'Crossing The Line', artist: 'Asia Minor', year: '1979', rating: ''},
		{ album: 'Cueille Le Jour', artist: 'Carpe Diem', year: '1976', rating: ''},
		{ album: 'Cuentos De Ayer Y De Hoy', artist: 'Nu', year: '1978', rating: ''},
		{ album: 'Culpeper\'S Orchard', artist: 'Culpeper\'S Orchard', year: '1971', rating: ''},
		{ album: 'The Cycle', artist: 'The Cycle', year: '1970', rating: ''},
		{ album: 'Cyclone', artist: 'Tangerine Dream', year: '1978', rating: ''},
		{ album: 'Czar', artist: 'Czar', year: '1970', rating: ''},
		{ album: 'Dance Of The Flames', artist: 'Guru Guru', year: '1974', rating: ''},
		{ album: 'Danger Money', artist: 'Uk', year: '1979', rating: ''},
		{ album: 'Danse Macabre', artist: 'Esperanto', year: '1974', rating: ''},
		{ album: 'Darwin!', artist: 'Banco Del Mutuo Soccorso', year: '1972', rating: ''},
		{ album: 'Dawn', artist: 'Eloy', year: '1976', rating: ''},
		{ album: 'Day Of Silver', artist: 'Aquarium', year: '1984', rating: '★★★'},
		{ album: 'De Michele-Erausquin', artist: 'Pastoral', year: '1979', rating: ''},
		{ album: 'Dead Faces', artist: 'Pholhas', year: '1973', rating: ''},
		{ album: 'Death Is A Great Gambler', artist: 'Coupla Prog', year: '1972', rating: ''},
		{ album: 'Death Walks Behind You', artist: 'Atomic Rooster', year: '1970', rating: ''},
		{ album: 'Deceptive Bends', artist: '10Cc', year: '1977', rating: ''},
		{ album: 'Dedicato A Frazz', artist: 'Semiramis', year: '1973', rating: ''},
		{ album: 'Dedicato A Giovanna G', artist: 'Hunka Munka', year: '1972', rating: ''},
		{ album: 'De-Loused In The Comatorium', artist: 'The Mars Volta', year: '2003', rating: ''},
		{ album: 'Demons And Wizards', artist: 'Uriah Deep', year: '1972', rating: ''},
		{ album: 'Den Of Iniquity', artist: 'The Norman Haines Band', year: '1971', rating: ''},
		{ album: 'Den Za Den', artist: 'Den Za Den', year: '1980', rating: ''},
		{ album: 'Dentro L\'Invisible', artist: 'Genfuoco', year: '1979', rating: ''},
		{ album: 'Depois Do Fim', artist: 'Bacamarte', year: '1983', rating: '★★★★'},
		{ album: 'Desatormentandonos', artist: 'Pescado Rabioso', year: '1972', rating: ''},
		{ album: 'Desert Places', artist: 'Satin White', year: '1974', rating: ''},
		{ album: 'Devil\'S Masquerade', artist: 'Syrius', year: '1971', rating: ''},
		{ album: 'Di Terra', artist: 'Banco Del Mutuo Soccorso', year: '1978', rating: ''},
		{ album: 'Dialog S Vesmirem', artist: 'Barnodaj', year: '1980', rating: '★★'},
		{ album: 'Different Roads', artist: 'Jake Jones', year: '1971', rating: ''},
		{ album: 'Dingly Dell', artist: 'Lindisfarne', year: '1972', rating: ''},
		{ album: 'Dinner At The Ritz', artist: 'City Boy', year: '1976', rating: ''},
		{ album: 'Dinner In Honor Of Demon', artist: 'Akuma No Bansan-Kai', year: '1976', rating: ''},
		{ album: 'Dinosaur Swamps', artist: 'The Flock', year: '1970', rating: ''},
		{ album: 'Dirge', artist: 'Mr. Sirius', year: '1994', rating: ''},
		{ album: 'Discipline', artist: 'King Crimson', year: '1981', rating: ''},
		{ album: 'Distant Echoes', artist: 'Jade Warrior', year: '1994', rating: ''},
		{ album: 'Distortions', artist: 'Blue Phantom', year: '1971', rating: ''},
		{ album: 'Do Not Disturb', artist: 'Van Der Graaf Generator', year: '2016', rating: ''},
		{ album: 'Do You Like It Here Now, Are You Settling In?', artist: 'Man', year: '1971', rating: ''},
		{ album: 'Dolce Acqua', artist: 'Delirium', year: '1971', rating: ''},
		{ album: 'Dopo Il Buio La Luce', artist: 'Salis', year: '1979', rating: ''},
		{ album: 'Douar Nevez (Terre Nouvelle)', artist: 'Dan Ar Braz', year: '1977', rating: ''},
		{ album: 'Down To Earth', artist: 'Nektar', year: '1974', rating: ''},
		{ album: 'Dr. Siegel\'S Fried Egg Shooting Machine', artist: 'Flied Egg', year: '1972', rating: ''},
		{ album: 'Drama', artist: 'Yes', year: '1980', rating: ''},
		{ album: 'The Dream Harbour', artist: 'Willowglass', year: '2013', rating: ''},
		{ album: 'Dreptul De A Visa', artist: 'Progresiv Tm', year: '1973', rating: ''},
		{ album: 'Drosselbart', artist: 'Drosselbart', year: '1970', rating: ''},
		{ album: 'Drugi Nacin', artist: 'Drugi Nacin', year: '1975', rating: ''},
		{ album: 'Drunk And Happy', artist: 'Prudence', year: '1973', rating: ''},
		{ album: 'Dschinn', artist: 'Dschinn', year: '1972', rating: ''},
		{ album: 'Dupa Melci', artist: 'Nicu Alifantis', year: '1979', rating: ''},
		{ album: 'Durazno Sangrando', artist: 'Invisible', year: '1975', rating: ''},
		{ album: 'Dynastie Crisis', artist: 'Dynastie Crisis', year: '1970', rating: ''},
		{ album: 'Eagle Rock', artist: 'Titanic', year: '1974', rating: ''},
		{ album: 'Earth', artist: 'Vangelis O Papathanassiou', year: '1973', rating: ''},
		{ album: 'East', artist: 'East', year: '1972', rating: ''},
		{ album: 'East River', artist: 'East River Consort', year: '1971', rating: ''},
		{ album: 'Eclipse', artist: 'Cano', year: '1978', rating: ''},
		{ album: 'The Edgar Broughton Band', artist: 'The Edgar Broughton Band', year: '1971', rating: ''},
		{ album: 'Ege Bamyasi', artist: 'Can', year: '1972', rating: ''},
		{ album: 'Egg', artist: 'Egg', year: '1970', rating: ''},
		{ album: 'Eider Stellaire I', artist: 'Eider Stellaire', year: '1981', rating: ''},
		{ album: 'Eight Days (A Personal Journey)', artist: 'Austin Roberts & Advent', year: '1976', rating: ''},
		{ album: 'El Jardin De Los Presentes', artist: 'Invisible', year: '1976', rating: ''},
		{ album: 'El Volantin', artist: 'Los Jaivas', year: '1971', rating: ''},
		{ album: 'Electric Food', artist: 'Electric Food', year: '1970', rating: ''},
		{ album: 'Electric Indian', artist: 'Dull Knife', year: '1971', rating: ''},
		{ album: 'Electric Savage', artist: 'Colosseum Ii', year: '1977', rating: ''},
		{ album: 'Electric Silence', artist: 'Dzyan', year: '1974', rating: ''},
		{ album: 'Electricity', artist: 'Aquarium', year: '1981', rating: ''},
		{ album: 'Elefanten', artist: 'Kebnekaise', year: '1977', rating: ''},
		{ album: 'Elegant Gypsy', artist: 'Ai Di Meola', year: '1977', rating: ''},
		{ album: 'Elektronik Turkuler', artist: 'Erkin Koray', year: '1974', rating: ''},
		{ album: 'Elements', artist: 'Flame Dream', year: '1979', rating: ''},
		{ album: 'Elements', artist: 'Roger Glover', year: '1990', rating: ''},
		{ album: 'Eli', artist: 'Jan Akkerman', year: '1976', rating: ''},
		{ album: 'Elixir', artist: 'Azahar', year: '1977', rating: ''},
		{ album: 'Eloy', artist: 'Eloy', year: '1971', rating: ''},
		{ album: 'Elysian Encounter', artist: 'Baker Gurvitz Army', year: '1975', rating: ''},
		{ album: 'Emancipated', artist: 'Sage', year: '1972', rating: ''},
		{ album: 'Emerson, Lake, & Palmer', artist: 'Emerson, Lake, & Palmer', year: '1970', rating: ''},
		{ album: 'Emile Jacotey', artist: 'Ange', year: '1975', rating: ''},
		{ album: 'The Empyreal Ballet', artist: 'Window', year: '1978', rating: ''},
		{ album: 'En Anna Heille Anteeksi', artist: 'Anki', year: '1975', rating: ''},
		{ album: 'An Ny Tid Ar Har...', artist: 'November', year: '1970', rating: ''},
		{ album: 'En Regardant Passer Le Temps', artist: 'Carpe Diem', year: '1976', rating: ''},
		{ album: 'End Of The World', artist: 'Aphtodites Child', year: '1968', rating: ''},
		{ album: 'Energy', artist: 'Energy', year: '1974', rating: ''},
		{ album: 'Enigma', artist: 'Enigma', year: '1971', rating: ''},
		{ album: 'Enigmatic', artist: 'Czeslaw Niemen', year: '1969', rating: ''},
		{ album: 'Ennea', artist: 'Chase', year: '1972', rating: ''},
		{ album: 'Epilog', artist: 'Anglagard', year: '1994', rating: ''},
		{ album: 'Epsilon', artist: 'Epsilon', year: '1971', rating: ''},
		{ album: 'Erlkoenig', artist: 'Erlkoenig', year: '1973', rating: ''},
		{ album: 'Eros', artist: 'Dun', year: '1981', rating: ''},
		{ album: 'Eros & Thanatos', artist: 'Haddad', year: '2009', rating: ''},
		{ album: 'Erwartung', artist: 'Eden', year: '1978', rating: ''},
		{ album: 'Escenes', artist: 'Gotic', year: '1978', rating: ''},
		{ album: 'Espacios', artist: 'Ave Rock', year: '1977', rating: ''},
		{ album: 'Espana Ano 75', artist: 'Granada', year: '1976', rating: ''},
		{ album: 'Esperanto Rock Orchestra', artist: 'Esperanto', year: '1973', rating: ''},
		{ album: 'At Epres...', artist: 'Memoriance', year: '1976', rating: ''},
		{ album: 'Etcetera', artist: 'Laghonia', year: '1971', rating: ''},
		{ album: '汚れた街にいても', artist: 'Ken Narita', year: '1972', rating: ''},
		{ album: 'Every Good Boy Deserves Favour', artist: 'The Moody Blues', year: '1971', rating: ''},
		{ album: 'Everybody Is Everybody Else', artist: 'Barclay James Harvest', year: '1974', rating: ''},
		{ album: 'Ezekiel', artist: 'Itoiz', year: '1980', rating: ''},
		{ album: 'Faculty Recital', artist: 'Peter Berkow & Friends', year: '1976', rating: ''},
		{ album: 'Faeria', artist: 'Foehn', year: '1985', rating: ''},
		{ album: 'Fairyport', artist: 'Wigwam', year: '1971', rating: ''},
		{ album: 'The Family', artist: 'Mashmakhan', year: '1971', rating: ''},
		{ album: 'Fandangos In Space', artist: 'Carmen', year: '1973', rating: ''},
		{ album: 'Fantasy Of Horses', artist: 'Rainbow Theatre', year: '1976', rating: ''},
		{ album: 'Faust Iv', artist: 'Faust', year: '1973', rating: ''},
		{ album: 'Fear Of The Dark', artist: 'Gordon Giltrap', year: '1978', rating: ''},
		{ album: 'Fearless, Tearless, And Even Less', artist: 'Circus', year: '1980', rating: ''},
		{ album: 'Fede, Speranza, Carita', artist: 'J.E.T.', year: '1972', rating: ''},
		{ album: 'Felona E Sorona', artist: 'Le Orme', year: '1973', rating: ''},
		{ album: 'Fenyes Nap', artist: 'Bright Sun', year: '1977', rating: ''},
		{ album: 'Fette Jahre', artist: 'Lokomotive Kreuzberg', year: '1975', rating: ''},
		{ album: 'Ffwd', artist: 'Ffwd', year: '1994', rating: ''},
		{ album: 'Fields', artist: 'Fields', year: '1971', rating: ''},
		{ album: 'The Fifth Word', artist: 'Novac', year: '1970', rating: ''},
		{ album: 'First Album', artist: 'Mo', year: '1976', rating: ''},
		{ album: 'First Base', artist: 'Babe Ruth', year: '1976', rating: ''},
		{ album: 'First Offense', artist: 'The Fents', year: '1972', rating: ''},
		{ album: 'The First Time', artist: 'Shlomo Yidov', year: '1978', rating: ''},
		{ album: 'First Utterance', artist: 'Comus', year: '1970', rating: ''},
		{ album: 'Fish Out Of Water', artist: 'Chris Squire', year: '1975', rating: ''},
		{ album: 'Fish Rising', artist: 'Steve Hillage', year: '1975', rating: ''},
		{ album: 'Fjarilar | Magen', artist: 'Ragnarok', year: '1979', rating: ''},
		{ album: 'Flasket Brinner', artist: 'Flasket Brinner', year: '1971', rating: ''},
		{ album: 'Floating', artist: 'Eloy', year: '1974', rating: ''},
		{ album: 'Floating World', artist: 'Jade Warrior', year: '1974', rating: ''},
		{ album: 'The Flock', artist: 'The Flock', year: '1969', rating: ''},
		{ album: 'Fly Away', artist: 'Minotaurus', year: '1978', rating: ''},
		{ album: 'Flying Teapot', artist: 'Gong', year: '1973', rating: ''},
		{ album: 'Focus 2', artist: 'Focus', year: '1971', rating: ''},
		{ album: 'Focus 3', artist: 'Focus', year: '1972', rating: ''},
		{ album: 'Focus Plays Focus', artist: 'Focus', year: '1970', rating: ''},
		{ album: 'Foetus', artist: 'Potemkine', year: '1976', rating: ''},
		{ album: 'Fog On The Tyne', artist: 'Lindisfarne', year: '1976', rating: ''},
		{ album: 'Folkjokeopus', artist: 'Roy Harper', year: '1969', rating: ''},
		{ album: 'Follow My Dream', artist: 'Sbb', year: '1978', rating: ''},
		{ album: 'Fool\'S Meeting', artist: 'Delivery', year: '1970', rating: ''},
		{ album: 'For Girls Who Plump In The Night', artist: 'Caravan', year: '1973', rating: ''},
		{ album: 'For You The Old Woman', artist: 'Mirthrandir', year: '1976', rating: ''},
		{ album: 'Formerly Anthrax', artist: 'Show Of Hands', year: '1970', rating: ''},
		{ album: 'Fountains Of Light', artist: 'Show Of Light', year: '1970', rating: ''},
		{ album: 'Four Moments', artist: 'Sebastian Hardie', year: '1975', rating: ''},
		{ album: 'The Four Seasons', artist: 'Oki Koichi', year: '1974', rating: ''},
		{ album: 'Foxtrot', artist: 'Genesis', year: '1972', rating: ''},
		{ album: 'Fragile', artist: 'Yes', year: '1971', rating: '★★★★★'},
		{ album: 'Framtiden Ar Ett Svavande Skepp, Forankrat I Forntiden', artist: 'Algarnas Tradgard', year: '1972', rating: ''},
		{ album: 'Frances The Mute', artist: 'The Mars Volta', year: '2005', rating: ''},
		{ album: 'Free Electric Sound', artist: 'Gila', year: '1971', rating: ''},
		{ album: 'Free Hand', artist: 'Gentle Giant', year: '1975', rating: ''},
		{ album: 'Friendship', artist: 'Junipher Greene', year: '1971', rating: ''},
		{ album: 'Frijid Pink', artist: 'Frijid Pink', year: '1970', rating: ''},
		{ album: 'Fritt Fall', artist: 'Kornet', year: '1977', rating: ''},
		{ album: 'Frob', artist: 'Frob', year: '1976', rating: ''},
		{ album: 'From Genesis To Revelations', artist: 'Genesis', year: '1969', rating: ''},
		{ album: 'From The New World', artist: 'Pell Mell', year: '1973', rating: ''},
		{ album: 'Frumpy 2', artist: 'Frumpy', year: '1971', rating: ''},
		{ album: 'Frutti Per Kagua', artist: 'Capitolo 6', year: '1972', rating: ''},
		{ album: 'Fuchsia', artist: 'Fuchsia', year: '1970', rating: ''},
		{ album: 'Funky Caravan', artist: 'Space Circus', year: '1978', rating: ''},
		{ album: 'Funky Steps', artist: 'Tranzam', year: '1974', rating: ''},
		{ album: 'Fusioon', artist: 'Fusioon', year: '1972', rating: ''},
		{ album: 'Fusioon 2', artist: 'Fusioon', year: '1974', rating: ''},
		{ album: 'Futurama', artist: 'Be+Bop Deluxe', year: '1975', rating: ''},
		{ album: 'Future Days', artist: 'Can', year: '1973', rating: ''},
		{ album: 'Future Legends', artist: 'Fruupp', year: '1973', rating: ''}
	];
	
});

jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.location = $(this).data("href");
	});
});